### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by camdez** [rejeep/ert-runner.el#18]
Both locally and on [Travis CI](https://travis-ci.org/rejeep/ert-runner.el):

```
17 scenarios (9 failed, 8 passed)
70 steps (9 failed, 4 skipped, 57 passed)
make[1]: *** [ecukes] Error 1
make: *** [test] Error 2
```

See [failed build on Travis](https://travis-ci.org/rejeep/ert-runner.el/jobs/46097214) for details.

**Comment by rejeep** [comment]
Isn't it just lovely when things break for you, even though you don't touch anything!? I updated the Travis config so that it should work. Still fails locally though, no idea why. Investigating...

**Comment by camdez** [comment]
Right?? I was completely baffled when I looked at the commit where the problem started.

**Comment by rejeep** [comment]
I still am. Don't understand the errors at all...

**Comment by rejeep** [comment]
I think I've located the issue in all versions except for 24.5, which seems to have a different error. The issue is the `spec` reporter that is broken in most recent versions, so I changed to the `dot` reporter. I will try to fix the broken spec reporter.

**Comment by rejeep** [comment]
Joy, all is well now!
