### ISSUE TITLE
loading fails if ERT_RUNNER_ARGS are not set

### ISSUE THREAD

**Issue by andreas-roehler** [rejeep/ert-runner.el#21]
Plains loading of the library should depend on setting of ERT_RUNNER_ARGS

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match(" " nil 0)
  split-string(nil " " nil)
  s-split(" " nil)
  (-reject (quote s-blank\?) (s-split " " (getenv "ERT_RUNNER_ARGS")))

**Comment by lunaryorn** [comment]
@andreas-roehler ert-runner is no library…

**Comment by rejeep** [comment]
@lunaryorn Would make sense to split it up to ert-runner and ert-runner-cli, like with Cask. That way it would be easier to unit test. Now there are only Ecukes tests.

**Comment by rejeep** [comment]
@andreas-roehler But like @lunaryorn said, it's not a library ATM, so you cant require it.

**Comment by rejeep** [comment]
Closing this.
