### ISSUE TITLE
Question: how to automatically add package directory on load-path

### ISSUE THREAD

**Issue by Fuco1** [rejeep/ert-runner.el#28]
I've been using ert-runner for the longest time and I always include this piece of code into the `test-helper.el` file

```elisp
(let ((dir (f-parent (f-dirname (f-this-file)))))
  (add-to-list 'load-path dir))
(require '<MY-PACKAGE>)
```

What this does essentially is it adds `../` on the `load-path`.  I can never get things to work without it as neither `cask load-path` would report the package's path there nor `require` finds the files.

However, I've noticed projects which don't do this and I can't figure out how/where to configure things to simply include the directory with `Cask` on the `load-path` (in fact, all the projects in the example section work just fine like that).

What do I need to do? :O

**Comment by rejeep** [comment]
Not really sure? Do you have an example project where this happens?

You can add something like `-L .` to `.ert-runner`.

I always load the package with an explicit path, for example: https://github.com/rejeep/f.el/blob/master/test/f-init.el#L42

**Comment by Fuco1** [comment]
thanks, `-L .` works :)

**Comment by rejeep** [comment]
You can add "-L ." to [.ert-runner](https://github.com/rejeep/ert-runner.el/blob/master/ert-runner.el#L326)

**Comment by fommil** [comment]
super weird, but after using `ert-runner` for years, I needed to start adding this to get my tests to pass (admittedly, I've probably only run it for the first time since 0.8.8 was released last year!)
