### ISSUE TITLE
ert-runner on Windows

### ISSUE THREAD

**Issue by sg2002** [rejeep/ert-runner.el#29]
Hello.

I've tried launching ert-runner on Windows and it does not work. I get:
```
cask exec: error: [Errno 2] No such file or directory
```

Adding --debug does not add any new output.

There's a ert-runner bash script, in my .cask project folder, but running it manually using msys bash, does not work.

**Comment by lunaryorn** [comment]
@sg2002 I don't think that ert-runner works on Windows.

**Comment by rejeep** [comment]
@sg2002 There is no explicit support for Windows. If you want you can add support for it, but then you would also have to maintain it, because no one else will.
