### ISSUE TITLE
Only print test output when it fails

### ISSUE THREAD

**Issue by Fuco1** [rejeep/ert-runner.el#31]
When the test passes, I don't really care about any messages the test produces.  I would just want to see all the dots.  If the test fails and we want to use some quick&dirty printf debugging, the tester should capture the output and print it.

Could we somehow wrap the test with `shut-up` or similar (ideally capturing the output to a string so we can later dump it in case of failure).  I'm not familiar with the internal test-running logic.

**Comment by Fuco1** [comment]
Okey, I see we have the `--quiet` option, then I propose we make that the default.

**Comment by rejeep** [comment]
Closing this via https://github.com/rejeep/ert-runner.el/pull/34
