### ISSUE TITLE
dot reporter output is not "online"

### ISSUE THREAD

**Issue by Fuco1** [rejeep/ert-runner.el#32]
On my emacs (GNU Emacs 24.5.2 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8) of 2015-07-09 on herakleitos) the dot reporter doesn't print anything before all the tests are over.  Shouldn't it print a dot as soon as the test passes?

**Comment by Fuco1** [comment]
After some investigation it seems that `ert-runner-message` only outputs to the terminal after newline.  Because all the dots are printed on the same line, the "flush" is never triggered.

**Comment by rejeep** [comment]
Yeah, I had the same issue in Ecukes, but solved it using Ansi CSI codes (https://github.com/ecukes/ecukes/blob/master/reporters/ecukes-reporter-dot.el#L21). I never got around to add it here.

Last time I check, there was no way to flush the buffer manually.

**Comment by Fuco1** [comment]
Would you mind pulling the dependency, or should I try to just inline the "up" character?

**Comment by rejeep** [comment]
I don't mind dependencies at all. It seems some Emacs devs don't want to include deps such as dash, f, s etc. I really don't agree with that and think deps is a great way of reusing code and achieve code quality.

**Comment by rejeep** [comment]
Btw, it already is a dependency https://github.com/rejeep/ert-runner.el/blob/master/ert-runner.el#L12 😄

**Comment by rejeep** [comment]
When I noticed this I also created an issue on the Emacs bug-tracker (https://lists.gnu.org/archive/html/bug-gnu-emacs/2013-09/msg00413.html), but nothing came out of it.

**Comment by Fuco1** [comment]
All right, I'll cook up a PR in the evening.  Thanks.

**Comment by rejeep** [comment]
👍
