### ISSUE TITLE
"Nonexistent files" test fails because of quoting style

### ISSUE THREAD

**Issue by phst** [rejeep/ert-runner.el#44]
The "nonexistent files" test fails for me because Emacs now uses Unicode quotes by default:

```
Then I should see error "/missing-test.el` does not exist"
      Test failed: ((should (s-contains\? expected ert-runner-error)) :form (s-contains\? "/missing-test.el` does not exist" "‘/path/to/ert-runner.el/features/project/test/missing-test.el‘ does not exist.
      ") :value nil)
```

Either you need to bind `text-quoting-style` or check for either ASCII or Unicode quotes.
(The quote itself is also incorrect; it's an opening quote, not a closing quote.)

**Comment by Fuco1** [comment]
Fixed in #51.
