### ISSUE TITLE
`ert--print-backtrace` has been removed in latest Emacs

### ISSUE THREAD

**Issue by qhuyduong** [rejeep/ert-runner.el#49]
`ert--print-backtrace` has been removed with this commit

https://github.com/emacs-mirror/emacs/commit/e09120d68694272ea5efbe13b16936b4382389d8

So `ert-runner` can't work with latest Emacs. Please help to fix.

Thanks

**Comment by anquegi** [comment]
Until, it will we updated we can use a workaround in test-helper.el, for emacs major-version bigger than 26:

(when (> emacs-major-version 26)
  (defalias 'ert--print-backtrace 'backtrace-to-string))


bad tests:

```
learn/emacs/neural-networks-and-chaos took 2s
➜ cask exec ert-runner

Test addition-test backtrace:


Test addition-test condition:

    (ert-test-failed
     ((should
       (=
	(+ 2 1)
	4))
      :form
      (= 3 4)
      :value nil))

F

Ran 1 test in 0.084 seconds
1 unexpected results:
   FAILED  addition-test
```

Corrected tests:

```
➜ cask exec ert-runner

.

Ran 1 test in 0.000 seconds
```

**Comment by cireu** [comment]
How about now? It's not an important issue but really annoying and confusing.

**Comment by seagle0128** [comment]
Any update?
